package xbuild;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.TaskAction;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.file.Files;
import java.util.Arrays;

import org.gradle.api.DefaultTask;

public class XBuild implements Plugin<Project> {
    @Override
    public void apply(Project project) {}

    /**
     * Usage is like:
     * 
     * tasks.register<ThisClassName>("generateJavaConstantsFile") {
     *   version = "1.2.3"
     *   className = "the.fully.qualified.class.to.write.the.file.To"
     * }
     */
    public static abstract class GenerateConstants extends DefaultTask {
        @Input
        public abstract Property<String> getVersion();
        
        @Input
        public abstract Property<String> getClassName();

        @TaskAction
        public void go() {
            String[] classNameComponents = getClassName().get().split("\\.");
            if (classNameComponents.length == 0) {
                throw new RuntimeException("Invalid value for 'className' -- '" + getClassName().get() + "'");
            }

            String packageName = Arrays.stream(classNameComponents)
                .limit(classNameComponents.length - 1)
                .reduce("", (in, accum) -> in.equals("") ? accum : (in + "." + accum));
            String className = classNameComponents[classNameComponents.length - 1];
            
            File path = getProject()
                .getLayout()
                .getProjectDirectory()
                .file("src/main/java/" + packageName.replaceAll("\\.", "/") + "/" + className + ".java")
                .getAsFile();

            try {
                Files.createDirectories(path.toPath().getParent());
                try (FileOutputStream out = new FileOutputStream(path)) {
                    out.write(GenerateConstants.generateConstantsFile(
                        packageName,
                        className,
                        getVersion().get()
                    ).getBytes("utf-8"));
                }
            }
            catch (Throwable e) {
                throw new RuntimeException(e);
            }
        }

        private static String generateConstantsFile(
            String packageName,
            String className,
            String version
        ) {
            return ""
                + "// THIS FILE WAS AUTOGENERATED BY A GRADLE BUILD STEP. DO NOT EDIT.\n"
                + "package " + packageName + ";\n"
                + "public final class " + className + " {\n"
                + "  public static final String version = \"" + version + "\";\n"
                + "}\n";
        }
    }

}
