/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asm.use;

public class TestDriver1 {
    public static void main(String[] args) {
        WillHaveSourceFileNameTransformed v = new WillHaveSourceFileNameTransformed();
        System.out.println(v.bar());
    }

    public int foo() {
        int i = 0;
        int j = 1;
        int k = 2;
        System.out.println(i);
        System.out.println(j);
        System.out.println(k);
        return i + j + k;
    }

    public String bar() {
        return "bar -> foo -> " + foo();
    }
}
